# Generated by Django 4.1.2 on 2023-04-05 07:58

import atm_api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('accountName', models.CharField(max_length=30)),
                ('accountNumber', models.CharField(max_length=30)),
                ('balance', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='AccountHolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usernameName', models.CharField(max_length=30)),
                ('pin', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField(default=0.0)),
                ('transactionType', models.CharField(choices=[('deposit', 'DEPOSIT'), ('withdrawal', 'WITHDRAWAL')], default=atm_api.models.AccountType['DEPOSIT'], max_length=64, unique=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='atm_api.account')),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='atm_api.accountholder')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='holder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='atm_api.accountholder'),
        ),
    ]
