# Generated by Django 4.1.2 on 2023-04-05 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atm_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountholder',
            old_name='usernameName',
            new_name='userName',
        ),
    ]
