# Generated by Django 4.2 on 2023-04-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atm_api', '0002_rename_usernamename_accountholder_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transactionType',
            field=models.CharField(max_length=20),
        ),
    ]
